// The subset of boxd's public API (boxd.api.v1.BoxdApi at boxd.sh:9443) that
// the boxd driver calls. It is cut from https://docs.boxd.sh/reference/grpc-proto
// with every field number unchanged, so it stays wire-compatible; fields the
// driver never reads are left out and skipped as unknown. To refresh it, copy
// the RPCs and messages from that page again and run `go generate`.
//
// The file name is what the protobuf registry knows this file by, and a
// duplicate panics at startup. Any program that embeds disco-vm links it, so
// it is not called api.proto. The package cannot change: it is part of every
// RPC's path. A program that also links boxd's own Go stubs would collide on
// it, and has to choose one.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: discobox_vm_boxd.proto

package boxdapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BoxdApi_CreateVm_FullMethodName                = "/boxd.api.v1.BoxdApi/CreateVm"
	BoxdApi_DestroyVm_FullMethodName               = "/boxd.api.v1.BoxdApi/DestroyVm"
	BoxdApi_StartVm_FullMethodName                 = "/boxd.api.v1.BoxdApi/StartVm"
	BoxdApi_StopVm_FullMethodName                  = "/boxd.api.v1.BoxdApi/StopVm"
	BoxdApi_GetVm_FullMethodName                   = "/boxd.api.v1.BoxdApi/GetVm"
	BoxdApi_Exec_FullMethodName                    = "/boxd.api.v1.BoxdApi/Exec"
	BoxdApi_Whoami_FullMethodName                  = "/boxd.api.v1.BoxdApi/Whoami"
	BoxdApi_UploadFileStream_FullMethodName        = "/boxd.api.v1.BoxdApi/UploadFileStream"
	BoxdApi_SuspendVm_FullMethodName               = "/boxd.api.v1.BoxdApi/SuspendVm"
	BoxdApi_ResumeVm_FullMethodName                = "/boxd.api.v1.BoxdApi/ResumeVm"
	BoxdApi_WakeVm_FullMethodName                  = "/boxd.api.v1.BoxdApi/WakeVm"
	BoxdApi_SetAutoSuspendTimeout_FullMethodName   = "/boxd.api.v1.BoxdApi/SetAutoSuspendTimeout"
	BoxdApi_SetAutoHibernateTimeout_FullMethodName = "/boxd.api.v1.BoxdApi/SetAutoHibernateTimeout"
	BoxdApi_CreateSnapshot_FullMethodName          = "/boxd.api.v1.BoxdApi/CreateSnapshot"
	BoxdApi_GetSnapshot_FullMethodName             = "/boxd.api.v1.BoxdApi/GetSnapshot"
	BoxdApi_DeleteSnapshot_FullMethodName          = "/boxd.api.v1.BoxdApi/DeleteSnapshot"
	BoxdApi_CreateVmFromSnapshot_FullMethodName    = "/boxd.api.v1.BoxdApi/CreateVmFromSnapshot"
	BoxdApi_ResizeVm_FullMethodName                = "/boxd.api.v1.BoxdApi/ResizeVm"
	BoxdApi_ListProxies_FullMethodName             = "/boxd.api.v1.BoxdApi/ListProxies"
	BoxdApi_SetProxyPort_FullMethodName            = "/boxd.api.v1.BoxdApi/SetProxyPort"
	BoxdApi_SetBotProtection_FullMethodName        = "/boxd.api.v1.BoxdApi/SetBotProtection"
)

// BoxdApiClient is the client API for BoxdApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BoxdApiClient interface {
	CreateVm(ctx context.Context, in *CreateVmRequest, opts ...grpc.CallOption) (*CreateVmResponse, error)
	DestroyVm(ctx context.Context, in *DestroyVmRequest, opts ...grpc.CallOption) (*DestroyVmResponse, error)
	StartVm(ctx context.Context, in *StartVmRequest, opts ...grpc.CallOption) (*StartVmResponse, error)
	StopVm(ctx context.Context, in *StopVmRequest, opts ...grpc.CallOption) (*StopVmResponse, error)
	// NOT_FOUND for an id/name with no matching machine, including a destroyed
	// one.
	GetVm(ctx context.Context, in *GetVmRequest, opts ...grpc.CallOption) (*GetVmResponse, error)
	// The first request chunk carries vm_id/command; later chunks carry stdin.
	// The stream ends with a final chunk carrying exit_code. Cancelling the
	// call kills the remote command.
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecChunk, ExecChunk], error)
	Whoami(ctx context.Context, in *WhoamiRequest, opts ...grpc.CallOption) (*WhoamiResponse, error)
	// The first chunk carries vm_id/path/total_size; later chunks carry bytes.
	UploadFileStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadFileChunk, UploadFileResponse], error)
	SuspendVm(ctx context.Context, in *SuspendVmRequest, opts ...grpc.CallOption) (*SuspendVmResponse, error)
	ResumeVm(ctx context.Context, in *ResumeVmRequest, opts ...grpc.CallOption) (*ResumeVmResponse, error)
	WakeVm(ctx context.Context, in *WakeVmRequest, opts ...grpc.CallOption) (*WakeVmResponse, error)
	SetAutoSuspendTimeout(ctx context.Context, in *SetAutoSuspendTimeoutRequest, opts ...grpc.CallOption) (*SetAutoSuspendTimeoutResponse, error)
	SetAutoHibernateTimeout(ctx context.Context, in *SetAutoHibernateTimeoutRequest, opts ...grpc.CallOption) (*SetAutoHibernateTimeoutResponse, error)
	// Memory + disk of a running VM, replicated and versioned (latest-only).
	CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error)
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error)
	DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error)
	CreateVmFromSnapshot(ctx context.Context, in *CreateVmFromSnapshotRequest, opts ...grpc.CallOption) (*CreateVmResponse, error)
	ResizeVm(ctx context.Context, in *ResizeVmRequest, opts ...grpc.CallOption) (*ResizeVmResponse, error)
	// Every machine has a default proxy at <machine>.<zone>: an HTTPS domain
	// whose TLS boxd terminates, forwarding HTTP to one port of the machine.
	ListProxies(ctx context.Context, in *ListProxiesRequest, opts ...grpc.CallOption) (*ListProxiesResponse, error)
	SetProxyPort(ctx context.Context, in *SetProxyPortRequest, opts ...grpc.CallOption) (*SetProxyPortResponse, error)
	// Bot protection challenges an HTTPS request that would wake a sleeping
	// machine on <machine>.<zone>. On by default.
	SetBotProtection(ctx context.Context, in *SetBotProtectionRequest, opts ...grpc.CallOption) (*SetBotProtectionResponse, error)
}

type boxdApiClient struct {
	cc grpc.ClientConnInterface
}

func NewBoxdApiClient(cc grpc.ClientConnInterface) BoxdApiClient {
	return &boxdApiClient{cc}
}

func (c *boxdApiClient) CreateVm(ctx context.Context, in *CreateVmRequest, opts ...grpc.CallOption) (*CreateVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVmResponse)
	err := c.cc.Invoke(ctx, BoxdApi_CreateVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) DestroyVm(ctx context.Context, in *DestroyVmRequest, opts ...grpc.CallOption) (*DestroyVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyVmResponse)
	err := c.cc.Invoke(ctx, BoxdApi_DestroyVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) StartVm(ctx context.Context, in *StartVmRequest, opts ...grpc.CallOption) (*StartVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartVmResponse)
	err := c.cc.Invoke(ctx, BoxdApi_StartVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) StopVm(ctx context.Context, in *StopVmRequest, opts ...grpc.CallOption) (*StopVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopVmResponse)
	err := c.cc.Invoke(ctx, BoxdApi_StopVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) GetVm(ctx context.Context, in *GetVmRequest, opts ...grpc.CallOption) (*GetVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVmResponse)
	err := c.cc.Invoke(ctx, BoxdApi_GetVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecChunk, ExecChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BoxdApi_ServiceDesc.Streams[0], BoxdApi_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecChunk, ExecChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BoxdApi_ExecClient = grpc.BidiStreamingClient[ExecChunk, ExecChunk]

func (c *boxdApiClient) Whoami(ctx context.Context, in *WhoamiRequest, opts ...grpc.CallOption) (*WhoamiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhoamiResponse)
	err := c.cc.Invoke(ctx, BoxdApi_Whoami_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) UploadFileStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadFileChunk, UploadFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BoxdApi_ServiceDesc.Streams[1], BoxdApi_UploadFileStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadFileChunk, UploadFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BoxdApi_UploadFileStreamClient = grpc.ClientStreamingClient[UploadFileChunk, UploadFileResponse]

func (c *boxdApiClient) SuspendVm(ctx context.Context, in *SuspendVmRequest, opts ...grpc.CallOption) (*SuspendVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendVmResponse)
	err := c.cc.Invoke(ctx, BoxdApi_SuspendVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) ResumeVm(ctx context.Context, in *ResumeVmRequest, opts ...grpc.CallOption) (*ResumeVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeVmResponse)
	err := c.cc.Invoke(ctx, BoxdApi_ResumeVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) WakeVm(ctx context.Context, in *WakeVmRequest, opts ...grpc.CallOption) (*WakeVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WakeVmResponse)
	err := c.cc.Invoke(ctx, BoxdApi_WakeVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) SetAutoSuspendTimeout(ctx context.Context, in *SetAutoSuspendTimeoutRequest, opts ...grpc.CallOption) (*SetAutoSuspendTimeoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAutoSuspendTimeoutResponse)
	err := c.cc.Invoke(ctx, BoxdApi_SetAutoSuspendTimeout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) SetAutoHibernateTimeout(ctx context.Context, in *SetAutoHibernateTimeoutRequest, opts ...grpc.CallOption) (*SetAutoHibernateTimeoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAutoHibernateTimeoutResponse)
	err := c.cc.Invoke(ctx, BoxdApi_SetAutoHibernateTimeout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSnapshotResponse)
	err := c.cc.Invoke(ctx, BoxdApi_CreateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSnapshotResponse)
	err := c.cc.Invoke(ctx, BoxdApi_GetSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSnapshotResponse)
	err := c.cc.Invoke(ctx, BoxdApi_DeleteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) CreateVmFromSnapshot(ctx context.Context, in *CreateVmFromSnapshotRequest, opts ...grpc.CallOption) (*CreateVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVmResponse)
	err := c.cc.Invoke(ctx, BoxdApi_CreateVmFromSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) ResizeVm(ctx context.Context, in *ResizeVmRequest, opts ...grpc.CallOption) (*ResizeVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResizeVmResponse)
	err := c.cc.Invoke(ctx, BoxdApi_ResizeVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) ListProxies(ctx context.Context, in *ListProxiesRequest, opts ...grpc.CallOption) (*ListProxiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProxiesResponse)
	err := c.cc.Invoke(ctx, BoxdApi_ListProxies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) SetProxyPort(ctx context.Context, in *SetProxyPortRequest, opts ...grpc.CallOption) (*SetProxyPortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetProxyPortResponse)
	err := c.cc.Invoke(ctx, BoxdApi_SetProxyPort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) SetBotProtection(ctx context.Context, in *SetBotProtectionRequest, opts ...grpc.CallOption) (*SetBotProtectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetBotProtectionResponse)
	err := c.cc.Invoke(ctx, BoxdApi_SetBotProtection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BoxdApiServer is the server API for BoxdApi service.
// All implementations must embed UnimplementedBoxdApiServer
// for forward compatibility.
type BoxdApiServer interface {
	CreateVm(context.Context, *CreateVmRequest) (*CreateVmResponse, error)
	DestroyVm(context.Context, *DestroyVmRequest) (*DestroyVmResponse, error)
	StartVm(context.Context, *StartVmRequest) (*StartVmResponse, error)
	StopVm(context.Context, *StopVmRequest) (*StopVmResponse, error)
	// NOT_FOUND for an id/name with no matching machine, including a destroyed
	// one.
	GetVm(context.Context, *GetVmRequest) (*GetVmResponse, error)
	// The first request chunk carries vm_id/command; later chunks carry stdin.
	// The stream ends with a final chunk carrying exit_code. Cancelling the
	// call kills the remote command.
	Exec(grpc.BidiStreamingServer[ExecChunk, ExecChunk]) error
	Whoami(context.Context, *WhoamiRequest) (*WhoamiResponse, error)
	// The first chunk carries vm_id/path/total_size; later chunks carry bytes.
	UploadFileStream(grpc.ClientStreamingServer[UploadFileChunk, UploadFileResponse]) error
	SuspendVm(context.Context, *SuspendVmRequest) (*SuspendVmResponse, error)
	ResumeVm(context.Context, *ResumeVmRequest) (*ResumeVmResponse, error)
	WakeVm(context.Context, *WakeVmRequest) (*WakeVmResponse, error)
	SetAutoSuspendTimeout(context.Context, *SetAutoSuspendTimeoutRequest) (*SetAutoSuspendTimeoutResponse, error)
	SetAutoHibernateTimeout(context.Context, *SetAutoHibernateTimeoutRequest) (*SetAutoHibernateTimeoutResponse, error)
	// Memory + disk of a running VM, replicated and versioned (latest-only).
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error)
	GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error)
	DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error)
	CreateVmFromSnapshot(context.Context, *CreateVmFromSnapshotRequest) (*CreateVmResponse, error)
	ResizeVm(context.Context, *ResizeVmRequest) (*ResizeVmResponse, error)
	// Every machine has a default proxy at <machine>.<zone>: an HTTPS domain
	// whose TLS boxd terminates, forwarding HTTP to one port of the machine.
	ListProxies(context.Context, *ListProxiesRequest) (*ListProxiesResponse, error)
	SetProxyPort(context.Context, *SetProxyPortRequest) (*SetProxyPortResponse, error)
	// Bot protection challenges an HTTPS request that would wake a sleeping
	// machine on <machine>.<zone>. On by default.
	SetBotProtection(context.Context, *SetBotProtectionRequest) (*SetBotProtectionResponse, error)
	mustEmbedUnimplementedBoxdApiServer()
}

// UnimplementedBoxdApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBoxdApiServer struct{}

func (UnimplementedBoxdApiServer) CreateVm(context.Context, *CreateVmRequest) (*CreateVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVm not implemented")
}
func (UnimplementedBoxdApiServer) DestroyVm(context.Context, *DestroyVmRequest) (*DestroyVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyVm not implemented")
}
func (UnimplementedBoxdApiServer) StartVm(context.Context, *StartVmRequest) (*StartVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartVm not implemented")
}
func (UnimplementedBoxdApiServer) StopVm(context.Context, *StopVmRequest) (*StopVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopVm not implemented")
}
func (UnimplementedBoxdApiServer) GetVm(context.Context, *GetVmRequest) (*GetVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVm not implemented")
}
func (UnimplementedBoxdApiServer) Exec(grpc.BidiStreamingServer[ExecChunk, ExecChunk]) error {
	return status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedBoxdApiServer) Whoami(context.Context, *WhoamiRequest) (*WhoamiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Whoami not implemented")
}
func (UnimplementedBoxdApiServer) UploadFileStream(grpc.ClientStreamingServer[UploadFileChunk, UploadFileResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadFileStream not implemented")
}
func (UnimplementedBoxdApiServer) SuspendVm(context.Context, *SuspendVmRequest) (*SuspendVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuspendVm not implemented")
}
func (UnimplementedBoxdApiServer) ResumeVm(context.Context, *ResumeVmRequest) (*ResumeVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeVm not implemented")
}
func (UnimplementedBoxdApiServer) WakeVm(context.Context, *WakeVmRequest) (*WakeVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WakeVm not implemented")
}
func (UnimplementedBoxdApiServer) SetAutoSuspendTimeout(context.Context, *SetAutoSuspendTimeoutRequest) (*SetAutoSuspendTimeoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAutoSuspendTimeout not implemented")
}
func (UnimplementedBoxdApiServer) SetAutoHibernateTimeout(context.Context, *SetAutoHibernateTimeoutRequest) (*SetAutoHibernateTimeoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAutoHibernateTimeout not implemented")
}
func (UnimplementedBoxdApiServer) CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedBoxdApiServer) GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedBoxdApiServer) DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedBoxdApiServer) CreateVmFromSnapshot(context.Context, *CreateVmFromSnapshotRequest) (*CreateVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVmFromSnapshot not implemented")
}
func (UnimplementedBoxdApiServer) ResizeVm(context.Context, *ResizeVmRequest) (*ResizeVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResizeVm not implemented")
}
func (UnimplementedBoxdApiServer) ListProxies(context.Context, *ListProxiesRequest) (*ListProxiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProxies not implemented")
}
func (UnimplementedBoxdApiServer) SetProxyPort(context.Context, *SetProxyPortRequest) (*SetProxyPortResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetProxyPort not implemented")
}
func (UnimplementedBoxdApiServer) SetBotProtection(context.Context, *SetBotProtectionRequest) (*SetBotProtectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBotProtection not implemented")
}
func (UnimplementedBoxdApiServer) mustEmbedUnimplementedBoxdApiServer() {}
func (UnimplementedBoxdApiServer) testEmbeddedByValue()                 {}

// UnsafeBoxdApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BoxdApiServer will
// result in compilation errors.
type UnsafeBoxdApiServer interface {
	mustEmbedUnimplementedBoxdApiServer()
}

func RegisterBoxdApiServer(s grpc.ServiceRegistrar, srv BoxdApiServer) {
	// If the following call panics, it indicates UnimplementedBoxdApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BoxdApi_ServiceDesc, srv)
}

func _BoxdApi_CreateVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).CreateVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_CreateVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).CreateVm(ctx, req.(*CreateVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_DestroyVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).DestroyVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_DestroyVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).DestroyVm(ctx, req.(*DestroyVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_StartVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).StartVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_StartVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).StartVm(ctx, req.(*StartVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_StopVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).StopVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_StopVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).StopVm(ctx, req.(*StopVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_GetVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).GetVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_GetVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).GetVm(ctx, req.(*GetVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BoxdApiServer).Exec(&grpc.GenericServerStream[ExecChunk, ExecChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BoxdApi_ExecServer = grpc.BidiStreamingServer[ExecChunk, ExecChunk]

func _BoxdApi_Whoami_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhoamiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).Whoami(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_Whoami_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).Whoami(ctx, req.(*WhoamiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_UploadFileStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BoxdApiServer).UploadFileStream(&grpc.GenericServerStream[UploadFileChunk, UploadFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BoxdApi_UploadFileStreamServer = grpc.ClientStreamingServer[UploadFileChunk, UploadFileResponse]

func _BoxdApi_SuspendVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).SuspendVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_SuspendVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).SuspendVm(ctx, req.(*SuspendVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_ResumeVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).ResumeVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_ResumeVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).ResumeVm(ctx, req.(*ResumeVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_WakeVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WakeVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).WakeVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_WakeVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).WakeVm(ctx, req.(*WakeVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_SetAutoSuspendTimeout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAutoSuspendTimeoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).SetAutoSuspendTimeout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_SetAutoSuspendTimeout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).SetAutoSuspendTimeout(ctx, req.(*SetAutoSuspendTimeoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_SetAutoHibernateTimeout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAutoHibernateTimeoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).SetAutoHibernateTimeout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_SetAutoHibernateTimeout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).SetAutoHibernateTimeout(ctx, req.(*SetAutoHibernateTimeoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).GetSnapshot(ctx, req.(*GetSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_DeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).DeleteSnapshot(ctx, req.(*DeleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_CreateVmFromSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVmFromSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).CreateVmFromSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_CreateVmFromSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).CreateVmFromSnapshot(ctx, req.(*CreateVmFromSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_ResizeVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizeVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).ResizeVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_ResizeVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).ResizeVm(ctx, req.(*ResizeVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_ListProxies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProxiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).ListProxies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_ListProxies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).ListProxies(ctx, req.(*ListProxiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_SetProxyPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetProxyPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).SetProxyPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_SetProxyPort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).SetProxyPort(ctx, req.(*SetProxyPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_SetBotProtection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBotProtectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).SetBotProtection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_SetBotProtection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).SetBotProtection(ctx, req.(*SetBotProtectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BoxdApi_ServiceDesc is the grpc.ServiceDesc for BoxdApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BoxdApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "boxd.api.v1.BoxdApi",
	HandlerType: (*BoxdApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVm",
			Handler:    _BoxdApi_CreateVm_Handler,
		},
		{
			MethodName: "DestroyVm",
			Handler:    _BoxdApi_DestroyVm_Handler,
		},
		{
			MethodName: "StartVm",
			Handler:    _BoxdApi_StartVm_Handler,
		},
		{
			MethodName: "StopVm",
			Handler:    _BoxdApi_StopVm_Handler,
		},
		{
			MethodName: "GetVm",
			Handler:    _BoxdApi_GetVm_Handler,
		},
		{
			MethodName: "Whoami",
			Handler:    _BoxdApi_Whoami_Handler,
		},
		{
			MethodName: "SuspendVm",
			Handler:    _BoxdApi_SuspendVm_Handler,
		},
		{
			MethodName: "ResumeVm",
			Handler:    _BoxdApi_ResumeVm_Handler,
		},
		{
			MethodName: "WakeVm",
			Handler:    _BoxdApi_WakeVm_Handler,
		},
		{
			MethodName: "SetAutoSuspendTimeout",
			Handler:    _BoxdApi_SetAutoSuspendTimeout_Handler,
		},
		{
			MethodName: "SetAutoHibernateTimeout",
			Handler:    _BoxdApi_SetAutoHibernateTimeout_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _BoxdApi_CreateSnapshot_Handler,
		},
		{
			MethodName: "GetSnapshot",
			Handler:    _BoxdApi_GetSnapshot_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _BoxdApi_DeleteSnapshot_Handler,
		},
		{
			MethodName: "CreateVmFromSnapshot",
			Handler:    _BoxdApi_CreateVmFromSnapshot_Handler,
		},
		{
			MethodName: "ResizeVm",
			Handler:    _BoxdApi_ResizeVm_Handler,
		},
		{
			MethodName: "ListProxies",
			Handler:    _BoxdApi_ListProxies_Handler,
		},
		{
			MethodName: "SetProxyPort",
			Handler:    _BoxdApi_SetProxyPort_Handler,
		},
		{
			MethodName: "SetBotProtection",
			Handler:    _BoxdApi_SetBotProtection_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exec",
			Handler:       _BoxdApi_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadFileStream",
			Handler:       _BoxdApi_UploadFileStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "discobox_vm_boxd.proto",
}
