// The subset of boxd's public API (boxd.api.v1.BoxdApi at boxd.sh:9443) that
// the boxd driver calls. It is cut from https://docs.boxd.sh/reference/grpc-proto
// with every field number unchanged, so it stays wire-compatible; fields the
// driver never reads are left out and skipped as unknown. To refresh it, copy
// the RPCs and messages from that page again and run `go generate`.
//
// The file name is what the protobuf registry knows this file by, and a
// duplicate panics at startup. Any program that embeds disco-vm links it, so
// it is not called api.proto. The package cannot change: it is part of every
// RPC's path. A program that also links boxd's own Go stubs would collide on
// it, and has to choose one.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: discobox_vm_boxd.proto

package boxdapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VmConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vcpu          uint32                 `protobuf:"varint,1,opt,name=vcpu,proto3" json:"vcpu,omitempty"`                                  // 0 = the org's default; else a size class
	MemoryBytes   uint64                 `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"` // 0 = the org's default; else a size class
	DiskBytes     uint64                 `protobuf:"varint,3,opt,name=disk_bytes,json=diskBytes,proto3" json:"disk_bytes,omitempty"`       // must be 0 or exactly the fixed 100 GiB
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmConfig) Reset() {
	*x = VmConfig{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmConfig) ProtoMessage() {}

func (x *VmConfig) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmConfig.ProtoReflect.Descriptor instead.
func (*VmConfig) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{0}
}

func (x *VmConfig) GetVcpu() uint32 {
	if x != nil {
		return x.Vcpu
	}
	return 0
}

func (x *VmConfig) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *VmConfig) GetDiskBytes() uint64 {
	if x != nil {
		return x.DiskBytes
	}
	return 0
}

type CreateVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImageRef      string                 `protobuf:"bytes,2,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	RestartPolicy string                 `protobuf:"bytes,7,opt,name=restart_policy,json=restartPolicy,proto3" json:"restart_policy,omitempty"` // "always" | "never"
	Config        *VmConfig              `protobuf:"bytes,8,opt,name=config,proto3" json:"config,omitempty"`
	Org           string                 `protobuf:"bytes,9,opt,name=org,proto3" json:"org,omitempty"`
	Isolated      bool                   `protobuf:"varint,12,opt,name=isolated,proto3" json:"isolated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVmRequest) Reset() {
	*x = CreateVmRequest{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmRequest) ProtoMessage() {}

func (x *CreateVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmRequest.ProtoReflect.Descriptor instead.
func (*CreateVmRequest) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVmRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVmRequest) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *CreateVmRequest) GetRestartPolicy() string {
	if x != nil {
		return x.RestartPolicy
	}
	return ""
}

func (x *CreateVmRequest) GetConfig() *VmConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateVmRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *CreateVmRequest) GetIsolated() bool {
	if x != nil {
		return x.Isolated
	}
	return false
}

type CreateVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PublicIp      string                 `protobuf:"bytes,3,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	BootTimeMs    uint64                 `protobuf:"varint,7,opt,name=boot_time_ms,json=bootTimeMs,proto3" json:"boot_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVmResponse) Reset() {
	*x = CreateVmResponse{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmResponse) ProtoMessage() {}

func (x *CreateVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmResponse.ProtoReflect.Descriptor instead.
func (*CreateVmResponse) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{2}
}

func (x *CreateVmResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CreateVmResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVmResponse) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *CreateVmResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateVmResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateVmResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateVmResponse) GetBootTimeMs() uint64 {
	if x != nil {
		return x.BootTimeMs
	}
	return 0
}

type DestroyVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyVmRequest) Reset() {
	*x = DestroyVmRequest{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyVmRequest) ProtoMessage() {}

func (x *DestroyVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyVmRequest.ProtoReflect.Descriptor instead.
func (*DestroyVmRequest) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{3}
}

func (x *DestroyVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type DestroyVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyVmResponse) Reset() {
	*x = DestroyVmResponse{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyVmResponse) ProtoMessage() {}

func (x *DestroyVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyVmResponse.ProtoReflect.Descriptor instead.
func (*DestroyVmResponse) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{4}
}

type StartVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVmRequest) Reset() {
	*x = StartVmRequest{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVmRequest) ProtoMessage() {}

func (x *StartVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVmRequest.ProtoReflect.Descriptor instead.
func (*StartVmRequest) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{5}
}

func (x *StartVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type StartVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVmResponse) Reset() {
	*x = StartVmResponse{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVmResponse) ProtoMessage() {}

func (x *StartVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVmResponse.ProtoReflect.Descriptor instead.
func (*StartVmResponse) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{6}
}

type StopVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVmRequest) Reset() {
	*x = StopVmRequest{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVmRequest) ProtoMessage() {}

func (x *StopVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVmRequest.ProtoReflect.Descriptor instead.
func (*StopVmRequest) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{7}
}

func (x *StopVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type StopVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVmResponse) Reset() {
	*x = StopVmResponse{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVmResponse) ProtoMessage() {}

func (x *StopVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVmResponse.ProtoReflect.Descriptor instead.
func (*StopVmResponse) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{8}
}

type SuspendVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendVmRequest) Reset() {
	*x = SuspendVmRequest{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendVmRequest) ProtoMessage() {}

func (x *SuspendVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendVmRequest.ProtoReflect.Descriptor instead.
func (*SuspendVmRequest) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{9}
}

func (x *SuspendVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type SuspendVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuspendUs     uint64                 `protobuf:"varint,1,opt,name=suspend_us,json=suspendUs,proto3" json:"suspend_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendVmResponse) Reset() {
	*x = SuspendVmResponse{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendVmResponse) ProtoMessage() {}

func (x *SuspendVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendVmResponse.ProtoReflect.Descriptor instead.
func (*SuspendVmResponse) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{10}
}

func (x *SuspendVmResponse) GetSuspendUs() uint64 {
	if x != nil {
		return x.SuspendUs
	}
	return 0
}

type ResumeVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeVmRequest) Reset() {
	*x = ResumeVmRequest{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeVmRequest) ProtoMessage() {}

func (x *ResumeVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeVmRequest.ProtoReflect.Descriptor instead.
func (*ResumeVmRequest) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{11}
}

func (x *ResumeVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type ResumeVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResumeUs      uint64                 `protobuf:"varint,1,opt,name=resume_us,json=resumeUs,proto3" json:"resume_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeVmResponse) Reset() {
	*x = ResumeVmResponse{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeVmResponse) ProtoMessage() {}

func (x *ResumeVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeVmResponse.ProtoReflect.Descriptor instead.
func (*ResumeVmResponse) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{12}
}

func (x *ResumeVmResponse) GetResumeUs() uint64 {
	if x != nil {
		return x.ResumeUs
	}
	return 0
}

type WakeVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WakeVmRequest) Reset() {
	*x = WakeVmRequest{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakeVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakeVmRequest) ProtoMessage() {}

func (x *WakeVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakeVmRequest.ProtoReflect.Descriptor instead.
func (*WakeVmRequest) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{13}
}

func (x *WakeVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type WakeVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WakeVmResponse) Reset() {
	*x = WakeVmResponse{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakeVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakeVmResponse) ProtoMessage() {}

func (x *WakeVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakeVmResponse.ProtoReflect.Descriptor instead.
func (*WakeVmResponse) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{14}
}

type SetAutoSuspendTimeoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	TimeoutSecs   uint32                 `protobuf:"varint,2,opt,name=timeout_secs,json=timeoutSecs,proto3" json:"timeout_secs,omitempty"` // 0 = disable
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAutoSuspendTimeoutRequest) Reset() {
	*x = SetAutoSuspendTimeoutRequest{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAutoSuspendTimeoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAutoSuspendTimeoutRequest) ProtoMessage() {}

func (x *SetAutoSuspendTimeoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAutoSuspendTimeoutRequest.ProtoReflect.Descriptor instead.
func (*SetAutoSuspendTimeoutRequest) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{15}
}

func (x *SetAutoSuspendTimeoutRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *SetAutoSuspendTimeoutRequest) GetTimeoutSecs() uint32 {
	if x != nil {
		return x.TimeoutSecs
	}
	return 0
}

type SetAutoSuspendTimeoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAutoSuspendTimeoutResponse) Reset() {
	*x = SetAutoSuspendTimeoutResponse{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAutoSuspendTimeoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAutoSuspendTimeoutResponse) ProtoMessage() {}

func (x *SetAutoSuspendTimeoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAutoSuspendTimeoutResponse.ProtoReflect.Descriptor instead.
func (*SetAutoSuspendTimeoutResponse) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{16}
}

type SetAutoHibernateTimeoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	TimeoutSecs   uint32                 `protobuf:"varint,2,opt,name=timeout_secs,json=timeoutSecs,proto3" json:"timeout_secs,omitempty"` // 0 = disable
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAutoHibernateTimeoutRequest) Reset() {
	*x = SetAutoHibernateTimeoutRequest{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAutoHibernateTimeoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAutoHibernateTimeoutRequest) ProtoMessage() {}

func (x *SetAutoHibernateTimeoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAutoHibernateTimeoutRequest.ProtoReflect.Descriptor instead.
func (*SetAutoHibernateTimeoutRequest) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{17}
}

func (x *SetAutoHibernateTimeoutRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *SetAutoHibernateTimeoutRequest) GetTimeoutSecs() uint32 {
	if x != nil {
		return x.TimeoutSecs
	}
	return 0
}

type SetAutoHibernateTimeoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAutoHibernateTimeoutResponse) Reset() {
	*x = SetAutoHibernateTimeoutResponse{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAutoHibernateTimeoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAutoHibernateTimeoutResponse) ProtoMessage() {}

func (x *SetAutoHibernateTimeoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAutoHibernateTimeoutResponse.ProtoReflect.Descriptor instead.
func (*SetAutoHibernateTimeoutResponse) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{18}
}

type GetVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmRequest) Reset() {
	*x = GetVmRequest{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmRequest) ProtoMessage() {}

func (x *GetVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmRequest.ProtoReflect.Descriptor instead.
func (*GetVmRequest) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{19}
}

func (x *GetVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type GetVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageRef      string                 `protobuf:"bytes,3,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	RestartPolicy string                 `protobuf:"bytes,6,opt,name=restart_policy,json=restartPolicy,proto3" json:"restart_policy,omitempty"`
	Vcpu          uint32                 `protobuf:"varint,15,opt,name=vcpu,proto3" json:"vcpu,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,16,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmResponse) Reset() {
	*x = GetVmResponse{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmResponse) ProtoMessage() {}

func (x *GetVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmResponse.ProtoReflect.Descriptor instead.
func (*GetVmResponse) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{20}
}

func (x *GetVmResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *GetVmResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetVmResponse) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *GetVmResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetVmResponse) GetRestartPolicy() string {
	if x != nil {
		return x.RestartPolicy
	}
	return ""
}

func (x *GetVmResponse) GetVcpu() uint32 {
	if x != nil {
		return x.Vcpu
	}
	return 0
}

func (x *GetVmResponse) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

type ExecChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Stdin         bool                   `protobuf:"varint,2,opt,name=stdin,proto3" json:"stdin,omitempty"`
	Tty           bool                   `protobuf:"varint,3,opt,name=tty,proto3" json:"tty,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	VmId          string                 `protobuf:"bytes,5,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,6,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	IsStderr      bool                   `protobuf:"varint,10,opt,name=is_stderr,json=isStderr,proto3" json:"is_stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecChunk) Reset() {
	*x = ExecChunk{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecChunk) ProtoMessage() {}

func (x *ExecChunk) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecChunk.ProtoReflect.Descriptor instead.
func (*ExecChunk) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{21}
}

func (x *ExecChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecChunk) GetStdin() bool {
	if x != nil {
		return x.Stdin
	}
	return false
}

func (x *ExecChunk) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *ExecChunk) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecChunk) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ExecChunk) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecChunk) GetIsStderr() bool {
	if x != nil {
		return x.IsStderr
	}
	return false
}

type WhoamiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoamiRequest) Reset() {
	*x = WhoamiRequest{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoamiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoamiRequest) ProtoMessage() {}

func (x *WhoamiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoamiRequest.ProtoReflect.Descriptor instead.
func (*WhoamiRequest) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{22}
}

type WhoamiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoamiResponse) Reset() {
	*x = WhoamiResponse{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoamiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoamiResponse) ProtoMessage() {}

func (x *WhoamiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoamiResponse.ProtoReflect.Descriptor instead.
func (*WhoamiResponse) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{23}
}

func (x *WhoamiResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WhoamiResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type UploadFileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	TotalSize     uint64                 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileChunk) Reset() {
	*x = UploadFileChunk{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileChunk) ProtoMessage() {}

func (x *UploadFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileChunk.ProtoReflect.Descriptor instead.
func (*UploadFileChunk) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{24}
}

func (x *UploadFileChunk) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *UploadFileChunk) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UploadFileChunk) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *UploadFileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  uint64                 `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{25}
}

func (x *UploadFileResponse) GetBytesWritten() uint64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type CreateSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vm            string                 `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`     // must be running
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // unique per owner; re-saving bumps the version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{26}
}

func (x *CreateSnapshotRequest) GetVm() string {
	if x != nil {
		return x.Vm
	}
	return ""
}

func (x *CreateSnapshotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "pending" until the capture is stored
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotResponse) Reset() {
	*x = CreateSnapshotResponse{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotResponse) ProtoMessage() {}

func (x *CreateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CreateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{27}
}

func (x *CreateSnapshotResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *CreateSnapshotResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSnapshotResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CreateSnapshotResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SnapshotInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "pending" | "ready" | "failed"
	SizeBytes     uint64                 `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Vcpu          uint32                 `protobuf:"varint,9,opt,name=vcpu,proto3" json:"vcpu,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,10,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotInfo) Reset() {
	*x = SnapshotInfo{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotInfo) ProtoMessage() {}

func (x *SnapshotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotInfo.ProtoReflect.Descriptor instead.
func (*SnapshotInfo) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{28}
}

func (x *SnapshotInfo) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *SnapshotInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SnapshotInfo) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SnapshotInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SnapshotInfo) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *SnapshotInfo) GetVcpu() uint32 {
	if x != nil {
		return x.Vcpu
	}
	return 0
}

func (x *SnapshotInfo) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

type GetSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Org           string                 `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{29}
}

func (x *GetSnapshotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSnapshotRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

type GetSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *SnapshotInfo          `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotResponse) Reset() {
	*x = GetSnapshotResponse{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotResponse) ProtoMessage() {}

func (x *GetSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{30}
}

func (x *GetSnapshotResponse) GetSnapshot() *SnapshotInfo {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type DeleteSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Org           string                 `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotRequest) Reset() {
	*x = DeleteSnapshotRequest{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotRequest) ProtoMessage() {}

func (x *DeleteSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotRequest.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteSnapshotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteSnapshotRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

type DeleteSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotResponse) Reset() {
	*x = DeleteSnapshotResponse{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotResponse) ProtoMessage() {}

func (x *DeleteSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotResponse.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{32}
}

type CreateVmFromSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      string                 `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Config        *VmConfig              `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Org           string                 `protobuf:"bytes,4,opt,name=org,proto3" json:"org,omitempty"`
	Isolated      bool                   `protobuf:"varint,5,opt,name=isolated,proto3" json:"isolated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVmFromSnapshotRequest) Reset() {
	*x = CreateVmFromSnapshotRequest{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmFromSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmFromSnapshotRequest) ProtoMessage() {}

func (x *CreateVmFromSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmFromSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateVmFromSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{33}
}

func (x *CreateVmFromSnapshotRequest) GetSnapshot() string {
	if x != nil {
		return x.Snapshot
	}
	return ""
}

func (x *CreateVmFromSnapshotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVmFromSnapshotRequest) GetConfig() *VmConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateVmFromSnapshotRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *CreateVmFromSnapshotRequest) GetIsolated() bool {
	if x != nil {
		return x.Isolated
	}
	return false
}

type ResizeVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`                       // VM name or id
	Vcpu          uint32                 `protobuf:"varint,2,opt,name=vcpu,proto3" json:"vcpu,omitempty"`                                  // names a size class (0 = derive from memory_bytes)
	MemoryBytes   uint64                 `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"` // names a size class (0 = derive from vcpu)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeVmRequest) Reset() {
	*x = ResizeVmRequest{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeVmRequest) ProtoMessage() {}

func (x *ResizeVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeVmRequest.ProtoReflect.Descriptor instead.
func (*ResizeVmRequest) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{34}
}

func (x *ResizeVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ResizeVmRequest) GetVcpu() uint32 {
	if x != nil {
		return x.Vcpu
	}
	return 0
}

func (x *ResizeVmRequest) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

type ResizeVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vcpu          uint32                 `protobuf:"varint,1,opt,name=vcpu,proto3" json:"vcpu,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Rebooted      bool                   `protobuf:"varint,3,opt,name=rebooted,proto3" json:"rebooted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeVmResponse) Reset() {
	*x = ResizeVmResponse{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeVmResponse) ProtoMessage() {}

func (x *ResizeVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeVmResponse.ProtoReflect.Descriptor instead.
func (*ResizeVmResponse) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{35}
}

func (x *ResizeVmResponse) GetVcpu() uint32 {
	if x != nil {
		return x.Vcpu
	}
	return 0
}

func (x *ResizeVmResponse) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResizeVmResponse) GetRebooted() bool {
	if x != nil {
		return x.Rebooted
	}
	return false
}

type ListProxiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vm            string                 `protobuf:"bytes,2,opt,name=vm,proto3" json:"vm,omitempty"` // machine id OR name; empty = every proxy the caller can see
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProxiesRequest) Reset() {
	*x = ListProxiesRequest{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProxiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProxiesRequest) ProtoMessage() {}

func (x *ListProxiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProxiesRequest.ProtoReflect.Descriptor instead.
func (*ListProxiesRequest) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{36}
}

func (x *ListProxiesRequest) GetVm() string {
	if x != nil {
		return x.Vm
	}
	return ""
}

type ListProxiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proxies       []*ProxyInfo           `protobuf:"bytes,1,rep,name=proxies,proto3" json:"proxies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProxiesResponse) Reset() {
	*x = ListProxiesResponse{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProxiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProxiesResponse) ProtoMessage() {}

func (x *ListProxiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProxiesResponse.ProtoReflect.Descriptor instead.
func (*ListProxiesResponse) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{37}
}

func (x *ListProxiesResponse) GetProxies() []*ProxyInfo {
	if x != nil {
		return x.Proxies
	}
	return nil
}

type ProxyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VmName        string                 `protobuf:"bytes,2,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	IsDefault     bool                   `protobuf:"varint,5,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	VmId          string                 `protobuf:"bytes,7,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	PortMode      string                 `protobuf:"bytes,8,opt,name=port_mode,json=portMode,proto3" json:"port_mode,omitempty"`                 // "locked" | "auto"
	EffectivePort uint32                 `protobuf:"varint,9,opt,name=effective_port,json=effectivePort,proto3" json:"effective_port,omitempty"` // the port traffic lands on
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyInfo) Reset() {
	*x = ProxyInfo{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyInfo) ProtoMessage() {}

func (x *ProxyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyInfo.ProtoReflect.Descriptor instead.
func (*ProxyInfo) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{38}
}

func (x *ProxyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProxyInfo) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *ProxyInfo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ProxyInfo) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *ProxyInfo) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ProxyInfo) GetPortMode() string {
	if x != nil {
		return x.PortMode
	}
	return ""
}

func (x *ProxyInfo) GetEffectivePort() uint32 {
	if x != nil {
		return x.EffectivePort
	}
	return 0
}

type SetProxyPortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port          string                 `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"` // a port number, or "auto" (the default proxy only)
	Vm            string                 `protobuf:"bytes,4,opt,name=vm,proto3" json:"vm,omitempty"`     // machine id OR name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProxyPortRequest) Reset() {
	*x = SetProxyPortRequest{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProxyPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProxyPortRequest) ProtoMessage() {}

func (x *SetProxyPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProxyPortRequest.ProtoReflect.Descriptor instead.
func (*SetProxyPortRequest) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{39}
}

func (x *SetProxyPortRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetProxyPortRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *SetProxyPortRequest) GetVm() string {
	if x != nil {
		return x.Vm
	}
	return ""
}

type SetProxyPortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProxyPortResponse) Reset() {
	*x = SetProxyPortResponse{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProxyPortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProxyPortResponse) ProtoMessage() {}

func (x *SetProxyPortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProxyPortResponse.ProtoReflect.Descriptor instead.
func (*SetProxyPortResponse) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{40}
}

type SetBotProtectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"` // name or id
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBotProtectionRequest) Reset() {
	*x = SetBotProtectionRequest{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBotProtectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBotProtectionRequest) ProtoMessage() {}

func (x *SetBotProtectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBotProtectionRequest.ProtoReflect.Descriptor instead.
func (*SetBotProtectionRequest) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{41}
}

func (x *SetBotProtectionRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *SetBotProtectionRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SetBotProtectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBotProtectionResponse) Reset() {
	*x = SetBotProtectionResponse{}
	mi := &file_discobox_vm_boxd_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBotProtectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBotProtectionResponse) ProtoMessage() {}

func (x *SetBotProtectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discobox_vm_boxd_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBotProtectionResponse.ProtoReflect.Descriptor instead.
func (*SetBotProtectionResponse) Descriptor() ([]byte, []int) {
	return file_discobox_vm_boxd_proto_rawDescGZIP(), []int{42}
}

var File_discobox_vm_boxd_proto protoreflect.FileDescriptor

const file_discobox_vm_boxd_proto_rawDesc = "" +
	"\n" +
	"\x16discobox_vm_boxd.proto\x12\vboxd.api.v1\"`\n" +
	"\bVmConfig\x12\x12\n" +
	"\x04vcpu\x18\x01 \x01(\rR\x04vcpu\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x04R\vmemoryBytes\x12\x1d\n" +
	"\n" +
	"disk_bytes\x18\x03 \x01(\x04R\tdiskBytes\"\xc6\x01\n" +
	"\x0fCreateVmRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\timage_ref\x18\x02 \x01(\tR\bimageRef\x12%\n" +
	"\x0erestart_policy\x18\a \x01(\tR\rrestartPolicy\x12-\n" +
	"\x06config\x18\b \x01(\v2\x15.boxd.api.v1.VmConfigR\x06config\x12\x10\n" +
	"\x03org\x18\t \x01(\tR\x03org\x12\x1a\n" +
	"\bisolated\x18\f \x01(\bR\bisolated\"\xba\x01\n" +
	"\x10CreateVmResponse\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tpublic_ip\x18\x03 \x01(\tR\bpublicIp\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12 \n" +
	"\fboot_time_ms\x18\a \x01(\x04R\n" +
	"bootTimeMs\"'\n" +
	"\x10DestroyVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"\x13\n" +
	"\x11DestroyVmResponse\"%\n" +
	"\x0eStartVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"\x11\n" +
	"\x0fStartVmResponse\"$\n" +
	"\rStopVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"\x10\n" +
	"\x0eStopVmResponse\"'\n" +
	"\x10SuspendVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"2\n" +
	"\x11SuspendVmResponse\x12\x1d\n" +
	"\n" +
	"suspend_us\x18\x01 \x01(\x04R\tsuspendUs\"&\n" +
	"\x0fResumeVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"/\n" +
	"\x10ResumeVmResponse\x12\x1b\n" +
	"\tresume_us\x18\x01 \x01(\x04R\bresumeUs\"$\n" +
	"\rWakeVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"\x10\n" +
	"\x0eWakeVmResponse\"V\n" +
	"\x1cSetAutoSuspendTimeoutRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12!\n" +
	"\ftimeout_secs\x18\x02 \x01(\rR\vtimeoutSecs\"\x1f\n" +
	"\x1dSetAutoSuspendTimeoutResponse\"X\n" +
	"\x1eSetAutoHibernateTimeoutRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12!\n" +
	"\ftimeout_secs\x18\x02 \x01(\rR\vtimeoutSecs\"!\n" +
	"\x1fSetAutoHibernateTimeoutResponse\"#\n" +
	"\fGetVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"\xcb\x01\n" +
	"\rGetVmResponse\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\timage_ref\x18\x03 \x01(\tR\bimageRef\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0erestart_policy\x18\x06 \x01(\tR\rrestartPolicy\x12\x12\n" +
	"\x04vcpu\x18\x0f \x01(\rR\x04vcpu\x12!\n" +
	"\fmemory_bytes\x18\x10 \x01(\x04R\vmemoryBytes\"\xb0\x01\n" +
	"\tExecChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05stdin\x18\x02 \x01(\bR\x05stdin\x12\x10\n" +
	"\x03tty\x18\x03 \x01(\bR\x03tty\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x13\n" +
	"\x05vm_id\x18\x05 \x01(\tR\x04vmId\x12\x1b\n" +
	"\texit_code\x18\x06 \x01(\x05R\bexitCode\x12\x1b\n" +
	"\tis_stderr\x18\n" +
	" \x01(\bR\bisStderr\"\x0f\n" +
	"\rWhoamiRequest\"L\n" +
	"\x0eWhoamiResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\"m\n" +
	"\x0fUploadFileChunk\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x04R\ttotalSize\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"9\n" +
	"\x12UploadFileResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x04R\fbytesWritten\";\n" +
	"\x15CreateSnapshotRequest\x12\x0e\n" +
	"\x02vm\x18\x01 \x01(\tR\x02vm\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x7f\n" +
	"\x16CreateSnapshotResponse\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\xcb\x01\n" +
	"\fSnapshotInfo\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x04R\tsizeBytes\x12\x12\n" +
	"\x04vcpu\x18\t \x01(\rR\x04vcpu\x12!\n" +
	"\fmemory_bytes\x18\n" +
	" \x01(\x04R\vmemoryBytes\":\n" +
	"\x12GetSnapshotRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03org\x18\x02 \x01(\tR\x03org\"L\n" +
	"\x13GetSnapshotResponse\x125\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x19.boxd.api.v1.SnapshotInfoR\bsnapshot\"=\n" +
	"\x15DeleteSnapshotRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03org\x18\x02 \x01(\tR\x03org\"\x18\n" +
	"\x16DeleteSnapshotResponse\"\xaa\x01\n" +
	"\x1bCreateVmFromSnapshotRequest\x12\x1a\n" +
	"\bsnapshot\x18\x01 \x01(\tR\bsnapshot\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x06config\x18\x03 \x01(\v2\x15.boxd.api.v1.VmConfigR\x06config\x12\x10\n" +
	"\x03org\x18\x04 \x01(\tR\x03org\x12\x1a\n" +
	"\bisolated\x18\x05 \x01(\bR\bisolated\"]\n" +
	"\x0fResizeVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04vcpu\x18\x02 \x01(\rR\x04vcpu\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x04R\vmemoryBytes\"e\n" +
	"\x10ResizeVmResponse\x12\x12\n" +
	"\x04vcpu\x18\x01 \x01(\rR\x04vcpu\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x04R\vmemoryBytes\x12\x1a\n" +
	"\brebooted\x18\x03 \x01(\bR\brebooted\"$\n" +
	"\x12ListProxiesRequest\x12\x0e\n" +
	"\x02vm\x18\x02 \x01(\tR\x02vm\"G\n" +
	"\x13ListProxiesResponse\x120\n" +
	"\aproxies\x18\x01 \x03(\v2\x16.boxd.api.v1.ProxyInfoR\aproxies\"\xc8\x01\n" +
	"\tProxyInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\avm_name\x18\x02 \x01(\tR\x06vmName\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"is_default\x18\x05 \x01(\bR\tisDefault\x12\x13\n" +
	"\x05vm_id\x18\a \x01(\tR\x04vmId\x12\x1b\n" +
	"\tport_mode\x18\b \x01(\tR\bportMode\x12%\n" +
	"\x0eeffective_port\x18\t \x01(\rR\reffectivePort\"M\n" +
	"\x13SetProxyPortRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\x12\x0e\n" +
	"\x02vm\x18\x04 \x01(\tR\x02vm\"\x16\n" +
	"\x14SetProxyPortResponse\"H\n" +
	"\x17SetBotProtectionRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"\x1a\n" +
	"\x18SetBotProtectionResponse2\xb3\r\n" +
	"\aBoxdApi\x12G\n" +
	"\bCreateVm\x12\x1c.boxd.api.v1.CreateVmRequest\x1a\x1d.boxd.api.v1.CreateVmResponse\x12J\n" +
	"\tDestroyVm\x12\x1d.boxd.api.v1.DestroyVmRequest\x1a\x1e.boxd.api.v1.DestroyVmResponse\x12D\n" +
	"\aStartVm\x12\x1b.boxd.api.v1.StartVmRequest\x1a\x1c.boxd.api.v1.StartVmResponse\x12A\n" +
	"\x06StopVm\x12\x1a.boxd.api.v1.StopVmRequest\x1a\x1b.boxd.api.v1.StopVmResponse\x12>\n" +
	"\x05GetVm\x12\x19.boxd.api.v1.GetVmRequest\x1a\x1a.boxd.api.v1.GetVmResponse\x12:\n" +
	"\x04Exec\x12\x16.boxd.api.v1.ExecChunk\x1a\x16.boxd.api.v1.ExecChunk(\x010\x01\x12A\n" +
	"\x06Whoami\x12\x1a.boxd.api.v1.WhoamiRequest\x1a\x1b.boxd.api.v1.WhoamiResponse\x12S\n" +
	"\x10UploadFileStream\x12\x1c.boxd.api.v1.UploadFileChunk\x1a\x1f.boxd.api.v1.UploadFileResponse(\x01\x12J\n" +
	"\tSuspendVm\x12\x1d.boxd.api.v1.SuspendVmRequest\x1a\x1e.boxd.api.v1.SuspendVmResponse\x12G\n" +
	"\bResumeVm\x12\x1c.boxd.api.v1.ResumeVmRequest\x1a\x1d.boxd.api.v1.ResumeVmResponse\x12A\n" +
	"\x06WakeVm\x12\x1a.boxd.api.v1.WakeVmRequest\x1a\x1b.boxd.api.v1.WakeVmResponse\x12n\n" +
	"\x15SetAutoSuspendTimeout\x12).boxd.api.v1.SetAutoSuspendTimeoutRequest\x1a*.boxd.api.v1.SetAutoSuspendTimeoutResponse\x12t\n" +
	"\x17SetAutoHibernateTimeout\x12+.boxd.api.v1.SetAutoHibernateTimeoutRequest\x1a,.boxd.api.v1.SetAutoHibernateTimeoutResponse\x12Y\n" +
	"\x0eCreateSnapshot\x12\".boxd.api.v1.CreateSnapshotRequest\x1a#.boxd.api.v1.CreateSnapshotResponse\x12P\n" +
	"\vGetSnapshot\x12\x1f.boxd.api.v1.GetSnapshotRequest\x1a .boxd.api.v1.GetSnapshotResponse\x12Y\n" +
	"\x0eDeleteSnapshot\x12\".boxd.api.v1.DeleteSnapshotRequest\x1a#.boxd.api.v1.DeleteSnapshotResponse\x12_\n" +
	"\x14CreateVmFromSnapshot\x12(.boxd.api.v1.CreateVmFromSnapshotRequest\x1a\x1d.boxd.api.v1.CreateVmResponse\x12G\n" +
	"\bResizeVm\x12\x1c.boxd.api.v1.ResizeVmRequest\x1a\x1d.boxd.api.v1.ResizeVmResponse\x12P\n" +
	"\vListProxies\x12\x1f.boxd.api.v1.ListProxiesRequest\x1a .boxd.api.v1.ListProxiesResponse\x12S\n" +
	"\fSetProxyPort\x12 .boxd.api.v1.SetProxyPortRequest\x1a!.boxd.api.v1.SetProxyPortResponse\x12_\n" +
	"\x10SetBotProtection\x12$.boxd.api.v1.SetBotProtectionRequest\x1a%.boxd.api.v1.SetBotProtectionResponseB=Z;github.com/discobox-ai/vm/pkg/machine/boxd/internal/boxdapib\x06proto3"

var (
	file_discobox_vm_boxd_proto_rawDescOnce sync.Once
	file_discobox_vm_boxd_proto_rawDescData []byte
)

func file_discobox_vm_boxd_proto_rawDescGZIP() []byte {
	file_discobox_vm_boxd_proto_rawDescOnce.Do(func() {
		file_discobox_vm_boxd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discobox_vm_boxd_proto_rawDesc), len(file_discobox_vm_boxd_proto_rawDesc)))
	})
	return file_discobox_vm_boxd_proto_rawDescData
}

var file_discobox_vm_boxd_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_discobox_vm_boxd_proto_goTypes = []any{
	(*VmConfig)(nil),                        // 0: boxd.api.v1.VmConfig
	(*CreateVmRequest)(nil),                 // 1: boxd.api.v1.CreateVmRequest
	(*CreateVmResponse)(nil),                // 2: boxd.api.v1.CreateVmResponse
	(*DestroyVmRequest)(nil),                // 3: boxd.api.v1.DestroyVmRequest
	(*DestroyVmResponse)(nil),               // 4: boxd.api.v1.DestroyVmResponse
	(*StartVmRequest)(nil),                  // 5: boxd.api.v1.StartVmRequest
	(*StartVmResponse)(nil),                 // 6: boxd.api.v1.StartVmResponse
	(*StopVmRequest)(nil),                   // 7: boxd.api.v1.StopVmRequest
	(*StopVmResponse)(nil),                  // 8: boxd.api.v1.StopVmResponse
	(*SuspendVmRequest)(nil),                // 9: boxd.api.v1.SuspendVmRequest
	(*SuspendVmResponse)(nil),               // 10: boxd.api.v1.SuspendVmResponse
	(*ResumeVmRequest)(nil),                 // 11: boxd.api.v1.ResumeVmRequest
	(*ResumeVmResponse)(nil),                // 12: boxd.api.v1.ResumeVmResponse
	(*WakeVmRequest)(nil),                   // 13: boxd.api.v1.WakeVmRequest
	(*WakeVmResponse)(nil),                  // 14: boxd.api.v1.WakeVmResponse
	(*SetAutoSuspendTimeoutRequest)(nil),    // 15: boxd.api.v1.SetAutoSuspendTimeoutRequest
	(*SetAutoSuspendTimeoutResponse)(nil),   // 16: boxd.api.v1.SetAutoSuspendTimeoutResponse
	(*SetAutoHibernateTimeoutRequest)(nil),  // 17: boxd.api.v1.SetAutoHibernateTimeoutRequest
	(*SetAutoHibernateTimeoutResponse)(nil), // 18: boxd.api.v1.SetAutoHibernateTimeoutResponse
	(*GetVmRequest)(nil),                    // 19: boxd.api.v1.GetVmRequest
	(*GetVmResponse)(nil),                   // 20: boxd.api.v1.GetVmResponse
	(*ExecChunk)(nil),                       // 21: boxd.api.v1.ExecChunk
	(*WhoamiRequest)(nil),                   // 22: boxd.api.v1.WhoamiRequest
	(*WhoamiResponse)(nil),                  // 23: boxd.api.v1.WhoamiResponse
	(*UploadFileChunk)(nil),                 // 24: boxd.api.v1.UploadFileChunk
	(*UploadFileResponse)(nil),              // 25: boxd.api.v1.UploadFileResponse
	(*CreateSnapshotRequest)(nil),           // 26: boxd.api.v1.CreateSnapshotRequest
	(*CreateSnapshotResponse)(nil),          // 27: boxd.api.v1.CreateSnapshotResponse
	(*SnapshotInfo)(nil),                    // 28: boxd.api.v1.SnapshotInfo
	(*GetSnapshotRequest)(nil),              // 29: boxd.api.v1.GetSnapshotRequest
	(*GetSnapshotResponse)(nil),             // 30: boxd.api.v1.GetSnapshotResponse
	(*DeleteSnapshotRequest)(nil),           // 31: boxd.api.v1.DeleteSnapshotRequest
	(*DeleteSnapshotResponse)(nil),          // 32: boxd.api.v1.DeleteSnapshotResponse
	(*CreateVmFromSnapshotRequest)(nil),     // 33: boxd.api.v1.CreateVmFromSnapshotRequest
	(*ResizeVmRequest)(nil),                 // 34: boxd.api.v1.ResizeVmRequest
	(*ResizeVmResponse)(nil),                // 35: boxd.api.v1.ResizeVmResponse
	(*ListProxiesRequest)(nil),              // 36: boxd.api.v1.ListProxiesRequest
	(*ListProxiesResponse)(nil),             // 37: boxd.api.v1.ListProxiesResponse
	(*ProxyInfo)(nil),                       // 38: boxd.api.v1.ProxyInfo
	(*SetProxyPortRequest)(nil),             // 39: boxd.api.v1.SetProxyPortRequest
	(*SetProxyPortResponse)(nil),            // 40: boxd.api.v1.SetProxyPortResponse
	(*SetBotProtectionRequest)(nil),         // 41: boxd.api.v1.SetBotProtectionRequest
	(*SetBotProtectionResponse)(nil),        // 42: boxd.api.v1.SetBotProtectionResponse
}
var file_discobox_vm_boxd_proto_depIdxs = []int32{
	0,  // 0: boxd.api.v1.CreateVmRequest.config:type_name -> boxd.api.v1.VmConfig
	28, // 1: boxd.api.v1.GetSnapshotResponse.snapshot:type_name -> boxd.api.v1.SnapshotInfo
	0,  // 2: boxd.api.v1.CreateVmFromSnapshotRequest.config:type_name -> boxd.api.v1.VmConfig
	38, // 3: boxd.api.v1.ListProxiesResponse.proxies:type_name -> boxd.api.v1.ProxyInfo
	1,  // 4: boxd.api.v1.BoxdApi.CreateVm:input_type -> boxd.api.v1.CreateVmRequest
	3,  // 5: boxd.api.v1.BoxdApi.DestroyVm:input_type -> boxd.api.v1.DestroyVmRequest
	5,  // 6: boxd.api.v1.BoxdApi.StartVm:input_type -> boxd.api.v1.StartVmRequest
	7,  // 7: boxd.api.v1.BoxdApi.StopVm:input_type -> boxd.api.v1.StopVmRequest
	19, // 8: boxd.api.v1.BoxdApi.GetVm:input_type -> boxd.api.v1.GetVmRequest
	21, // 9: boxd.api.v1.BoxdApi.Exec:input_type -> boxd.api.v1.ExecChunk
	22, // 10: boxd.api.v1.BoxdApi.Whoami:input_type -> boxd.api.v1.WhoamiRequest
	24, // 11: boxd.api.v1.BoxdApi.UploadFileStream:input_type -> boxd.api.v1.UploadFileChunk
	9,  // 12: boxd.api.v1.BoxdApi.SuspendVm:input_type -> boxd.api.v1.SuspendVmRequest
	11, // 13: boxd.api.v1.BoxdApi.ResumeVm:input_type -> boxd.api.v1.ResumeVmRequest
	13, // 14: boxd.api.v1.BoxdApi.WakeVm:input_type -> boxd.api.v1.WakeVmRequest
	15, // 15: boxd.api.v1.BoxdApi.SetAutoSuspendTimeout:input_type -> boxd.api.v1.SetAutoSuspendTimeoutRequest
	17, // 16: boxd.api.v1.BoxdApi.SetAutoHibernateTimeout:input_type -> boxd.api.v1.SetAutoHibernateTimeoutRequest
	26, // 17: boxd.api.v1.BoxdApi.CreateSnapshot:input_type -> boxd.api.v1.CreateSnapshotRequest
	29, // 18: boxd.api.v1.BoxdApi.GetSnapshot:input_type -> boxd.api.v1.GetSnapshotRequest
	31, // 19: boxd.api.v1.BoxdApi.DeleteSnapshot:input_type -> boxd.api.v1.DeleteSnapshotRequest
	33, // 20: boxd.api.v1.BoxdApi.CreateVmFromSnapshot:input_type -> boxd.api.v1.CreateVmFromSnapshotRequest
	34, // 21: boxd.api.v1.BoxdApi.ResizeVm:input_type -> boxd.api.v1.ResizeVmRequest
	36, // 22: boxd.api.v1.BoxdApi.ListProxies:input_type -> boxd.api.v1.ListProxiesRequest
	39, // 23: boxd.api.v1.BoxdApi.SetProxyPort:input_type -> boxd.api.v1.SetProxyPortRequest
	41, // 24: boxd.api.v1.BoxdApi.SetBotProtection:input_type -> boxd.api.v1.SetBotProtectionRequest
	2,  // 25: boxd.api.v1.BoxdApi.CreateVm:output_type -> boxd.api.v1.CreateVmResponse
	4,  // 26: boxd.api.v1.BoxdApi.DestroyVm:output_type -> boxd.api.v1.DestroyVmResponse
	6,  // 27: boxd.api.v1.BoxdApi.StartVm:output_type -> boxd.api.v1.StartVmResponse
	8,  // 28: boxd.api.v1.BoxdApi.StopVm:output_type -> boxd.api.v1.StopVmResponse
	20, // 29: boxd.api.v1.BoxdApi.GetVm:output_type -> boxd.api.v1.GetVmResponse
	21, // 30: boxd.api.v1.BoxdApi.Exec:output_type -> boxd.api.v1.ExecChunk
	23, // 31: boxd.api.v1.BoxdApi.Whoami:output_type -> boxd.api.v1.WhoamiResponse
	25, // 32: boxd.api.v1.BoxdApi.UploadFileStream:output_type -> boxd.api.v1.UploadFileResponse
	10, // 33: boxd.api.v1.BoxdApi.SuspendVm:output_type -> boxd.api.v1.SuspendVmResponse
	12, // 34: boxd.api.v1.BoxdApi.ResumeVm:output_type -> boxd.api.v1.ResumeVmResponse
	14, // 35: boxd.api.v1.BoxdApi.WakeVm:output_type -> boxd.api.v1.WakeVmResponse
	16, // 36: boxd.api.v1.BoxdApi.SetAutoSuspendTimeout:output_type -> boxd.api.v1.SetAutoSuspendTimeoutResponse
	18, // 37: boxd.api.v1.BoxdApi.SetAutoHibernateTimeout:output_type -> boxd.api.v1.SetAutoHibernateTimeoutResponse
	27, // 38: boxd.api.v1.BoxdApi.CreateSnapshot:output_type -> boxd.api.v1.CreateSnapshotResponse
	30, // 39: boxd.api.v1.BoxdApi.GetSnapshot:output_type -> boxd.api.v1.GetSnapshotResponse
	32, // 40: boxd.api.v1.BoxdApi.DeleteSnapshot:output_type -> boxd.api.v1.DeleteSnapshotResponse
	2,  // 41: boxd.api.v1.BoxdApi.CreateVmFromSnapshot:output_type -> boxd.api.v1.CreateVmResponse
	35, // 42: boxd.api.v1.BoxdApi.ResizeVm:output_type -> boxd.api.v1.ResizeVmResponse
	37, // 43: boxd.api.v1.BoxdApi.ListProxies:output_type -> boxd.api.v1.ListProxiesResponse
	40, // 44: boxd.api.v1.BoxdApi.SetProxyPort:output_type -> boxd.api.v1.SetProxyPortResponse
	42, // 45: boxd.api.v1.BoxdApi.SetBotProtection:output_type -> boxd.api.v1.SetBotProtectionResponse
	25, // [25:46] is the sub-list for method output_type
	4,  // [4:25] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_discobox_vm_boxd_proto_init() }
func file_discobox_vm_boxd_proto_init() {
	if File_discobox_vm_boxd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discobox_vm_boxd_proto_rawDesc), len(file_discobox_vm_boxd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discobox_vm_boxd_proto_goTypes,
		DependencyIndexes: file_discobox_vm_boxd_proto_depIdxs,
		MessageInfos:      file_discobox_vm_boxd_proto_msgTypes,
	}.Build()
	File_discobox_vm_boxd_proto = out.File
	file_discobox_vm_boxd_proto_goTypes = nil
	file_discobox_vm_boxd_proto_depIdxs = nil
}
